# Generated by Django 5.2.12 on 2026-03-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_remove_course_image_category_keywords_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='CourseImage',
        ),
    ]
